name: financial
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.1.0
  root_jailbreak_sniffer: ^1.1.0
  google_fonts: ^6.2.1
  highlight_text: ^1.8.0
  fl_chart: ^0.70.2
  dio: ^5.8.0+1
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  no_screenshot: ^0.3.1
  flutter_secure_storage: ^7.0.0
  local_auth: ^2.3.0
  shimmer: ^3.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie_jsons/
    - assets/images/
    - assets/icons/
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/english/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/english/Roboto-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/english/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/english/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/english/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/english/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/english/Roboto-Black.ttf
          weight: 900